# Generated by Django 4.2.7 on 2023-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_of_complited',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
